apiVersion: apps/v1
kind: Deployment
metadata:
  name: beer-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beer
  template:
    metadata:
      labels:
        app: beer
    spec:
      containers:
      - image: denisvitez/rso-beers:latest
        name: beers
        env:
        - name: KUMULUZEE_DISCOVERY_CLUSTER
          value: gcloud
        - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
          value: http://etcd:2379
        - name: KUMULUZEE_CONFIG_ETCD_HOSTS
          value: http://etcd:2379
        - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
          value: jdbc:postgresql://postgres-beers:5432/beers
        - name: KUMULUZEE_DATASOURCES0_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pg-pass
              key: KUMULUZEE_DATASOURCES0_PASSWORD
        ports:
        - containerPort: 5101
          name: server
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /health
            port: server
          initialDelaySeconds: 20
          periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: beer
spec:
  type: LoadBalancer
  ports:
  - port: 5101
    protocol: TCP
    targetPort: 5101
  selector:
    app: beer